### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by streamsteel** [ElCasagrande/Udacity-ML-Capstone-Project#2]
Your code is pretty good!
But some troubles I have when I run the code:

- I read the paper where used 12 features to analyze the dataset and why you only group by `user_id` and `skill_id`?
- I want to carry out a CART (classify tree) base on the data.How to achieve？
- how to use the model I saved where the file suffixed with `.hdf5` to test data?

**Comment by lccasagrande** [comment]
Hi streamsteel, 

> I read the paper where used 12 features to analyze the dataset and why you only group by user_id and skill_id?

I've grouped by user_id to form sequences of answers. The skill_id is encoded together with the answer because we want to find the probability of a student answering correctly a question B given its previous answers to other questions.

> I want to carry out a CART (classify tree) base on the data.How to achieve？

I cannot help on this. I believe it's better to start a fresh project if you are not using Deep Learning and wont use keras to build your model.

> how to use the model I saved where the file suffixed with .hdf5 to test data?

There is a jupyter notebook in this repository that you can follow to achieve this. Just omit the **Part 4** as you are not going to train your model. The rest of the code should remain the same. Remember to put the path to your .hdf5 file in the "best_model_file" in **Part 1**.

**Comment by streamsteel** [comment]
Thank you very much for your answer.
My current project needs to be implemented BKT(Bayesian knowledge tracking).Would you mind if I use part of your code to complete the paper?

**Comment by lccasagrande** [comment]
Not at all. Feel free to use it in your project, just not forget to give it the proper credits.
